# Generated by Django 4.0.2 on 2022-09-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopsdetail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='address',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
