# Generated by Django 4.0.2 on 2022-09-23 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shopsdetail', '0005_rename_groups_shopgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopgroup',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grp', to='Shopsdetail.shop'),
        ),
    ]
